sudo: false

language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

install:
  - npm install

deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_TOKEN}
  on:
    tags: true
